# Generated by Django 5.0.6 on 2025-07-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(help_text='The keyword to detect.', max_length=100, unique=True)),
                ('talking_point', models.TextField(blank=True, help_text='Optional talking point or suggestion associated with this keyword.')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this keyword is currently active for detection.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Identifier for the audio session.', max_length=255)),
                ('speaker_type', models.CharField(choices=[('prospect', 'Prospect'), ('agent', 'Agent'), ('unknown', 'Unknown')], default='unknown', help_text='Type of speaker (e.g., prospect, agent).', max_length=50)),
                ('text', models.TextField(help_text='The transcribed text.')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transcription',
                'verbose_name_plural': 'Transcriptions',
                'ordering': ['timestamp'],
            },
        ),
    ]
